name: Terraform Docs

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: terraform-docs-gh-actions
        uses: terraform-docs/gh-actions@v1.2.2
        with:
          config-file: .terraform-docs.yml
          git-push: true
          git-push-sign-off: true
